# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["tables"]

pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Iñigo Medina Blog
tagline:          'Code, Open Source'
url:              http://inigomedina.github.io
shorturl:         inigomedina.github.io

author:
  name:           'Iñigo Medina'
  url:            https://twitter.com/inigomedina

paginate:         0

# Custom vars
version:          1.0.0

github:
  repo:           github.com/inigomedina/inigomedina.github.io

# This is the list of pages to incldue in the header of the website.
pages_list:       
  About: '/about/'
  Feed: '/feed/'
  Twitter: 'http://twitter.com/inigomedina'
  GitHub: 'http://github.com/inigomedina'
  StackOverflow: 'http://stackoverflow.com/users/574093/inigomedina'

# Allow URL Redirects: 
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from
